### ISSUE TITLE
Setting up of design system / Style Guide

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#139]

**Comment by simileoluwa** [comment]
[(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=1319%3A1506)]
[](https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=10%3A673
)

**Comment by simileoluwa** [comment]
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=10%3A673
)
