### ISSUE TITLE
Event Hover Design

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#143]

**Comment by Mynah-b** [comment]
![Company Holiday Main View](https://user-images.githubusercontent.com/81077403/131821388-0d40a1a1-c445-42ee-be78-44fe2d712e48.png)
![Event details (hover) 1](https://user-images.githubusercontent.com/81077403/131821453-40bcc682-c23b-4f18-9989-5236c9c17ce4.png)
![Event details (click event) with reminder](https://user-images.githubusercontent.com/81077403/131821494-e88d20c3-9c17-44b4-a127-021ddd81992b.png)
[https://www.figma.com/file/w5Ra9MpePY6WvucmonhWcd/Untitled?node-id=0%3A1](url)

**Comment by UduakE** [comment]
@aayobam  Here
