### ISSUE TITLE
Develop database er-diagram for project

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#149]

**Comment by Bedeneche** [comment]
Chukwude Bede Chinecherem
chukwudegodwin@gmail.com
__Bede

**Comment by Bedeneche** [comment]
![database er-diagram](https://user-images.githubusercontent.com/88966183/131643946-8f57394e-06a4-4be8-aad8-6ceac8e0107e.PNG)
 Reminder_id in add event table connects with reminder_id in reminder table to show the relationship between them

**Comment by markessien** [comment]
Not a code ticket. You must deliver code this week

**Comment by aayobam** [comment]
can this ticket be closed.the codes are been implemented by others already.
