### ISSUE TITLE
Create middleware and utility for timezone

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#150]

**Comment by jamido1** [comment]
@⁨jamido1 create middleware and utility for timezone #150
Issue #150

**Comment by jamido1** [comment]
my changes have allowed you to select your timezones on the web
Username: hemingway
password: superuser1234
https://calendar.zuri.chat/admin/calendarapp/event/

**Comment by aayobam** [comment]
accepted
