### ISSUE TITLE
Create working event model and migrate

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#151]

**Comment by Ifeadewumi** [comment]
Slack username: @IfeAde1
Github username: @Ifeadewumi

**Comment by Ifeadewumi** [comment]
Live testable link for event model: https://calendar.zuri.chat/admin/login/?next=/admin/add/event
Username: admin
Password: Hemingway1

Working on getting the live login to work and repeat test.
Image for local machine successful Event creation attached. 
The working of model creation was confirmed successfully on the Backend Deputy's local machine.
![Local machine Event Model Successful](https://user-images.githubusercontent.com/61970764/131657563-e3007e61-8075-4c8b-9e1d-d229059f20eb.jpg)

**Comment by aayobam** [comment]
this task is accepted and has been merged.awaiting DevOps  to effect the changes

**Comment by markessien** [comment]
Cannot login

**Comment by Ifeadewumi** [comment]
Login issues now resolved. 
Live testable link: https://calendar.zuri.chat/admin/calendarapp/event/

Username: zc_calendar
Password: admin

Pull request: https://github.com/zurichat/zc_plugin_company_holiday_calendar/pull/172

**Comment by aayobam** [comment]
Task completed and confirmed working

**Comment by markessien** [comment]
ok
