### ISSUE TITLE
In serializer.py file create serializer class for event

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#153]

**Comment by 50-Course** [comment]
I would be taking up this Issue. Ref. #153

**Comment by 50-Course** [comment]
Solved: Test link: [Local endpoint](https://127.0.0.1:8000/api/v1/events)

**Comment by markessien** [comment]
Local endpoint for testing?

**Comment by 50-Course** [comment]
> Local endpoint for testing?

This code snippet allows the serialization of events data. It allows a persistent data storage format, ensuring events created by a prospect user is valid for a DB entry and query upon which CRUD endpoints may be performed.
https://calendar.zuri.chat/zuricalendar/search/

**Comment by aayobam** [comment]
The url you porovided i is someone else's work. this si not your assigned task.

**Comment by 50-Course** [comment]
Created the serialization class that serialize data from the user (this case, events) ensuring a safe method of data conversion and persistence. It converts the view and model to JSON data.

To see it in action: [](https://calendar.zuri.chat/zuricalendar/create_event/)

Slack name: @Codepunk
Email: sinmiwaye2001@gmail.com
