### ISSUE TITLE
develop LIST view and enpoint for event

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#156]
make use of class based view and create a working endpoint.You can test with postman

**Comment by Vicolas11** [comment]
Vicolas

**Comment by Vicolas11** [comment]
Live link: https://calendar.zuri.chat/zuricalendar/list-events/
SlackName: Vicolas
PR: #156

Return JSON Objects list of events.

**Comment by aayobam** [comment]
Accepted
