### ISSUE TITLE
develop CREATE view and enpoint for reminder

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#160]
make use of class based view and create a working endpoint.You can test with postman

**Comment by Trustidiong** [comment]
Trust

**Comment by Trustidiong** [comment]
My task is to enable a user be able to create reminders. Attached is a testable link of the task.

https://calendar.zuri.chat/zuricalendar/create-reminder/

slack username: Trust

**Comment by Trustidiong** [comment]
Can I handle this?
