### ISSUE TITLE
develop DESTROY view and enpoint for reminder

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#164]
make use of class based view and create a working endpoint.You can test with postman

**Comment by mrbazzan** [comment]
@Bazzan

**Comment by mrbazzan** [comment]
This endpoint is used to delete a particular reminder. The `reminder's id` is required.

To be able to delete a reminder, the reminder must exist.

Click on this link: https://calendar.zuri.chat/zuricalendar/delete-reminder/1/
Then click on the **delete button** on the page to succesfully delete a reminder.
