### ISSUE TITLE
Configure django rest framework and middlewares

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#165]

**Comment by aayobam** [comment]
I configured the django rest framework and the link below ensured it was properly configured
calendar.zuri.chat/api-auth/login

**Comment by markessien** [comment]
No link to code

**Comment by aayobam** [comment]
This is a configuration in the settings and project urls, it doesn't have a code. https://calendar.zuri.chat/api-auth/login is the testing link to detect if rest framework is properly configured or not.

**Comment by aayobam** [comment]
accepted and confirmed
