### ISSUE TITLE
Company holiday event custom recurrence

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#206]

**Comment by Muyiwa-Adebayo** [comment]
Screen 1 - Set Custom Recurrence 
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=2259%3A2596)

Screen 2 - Complete Custom Recurrence
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=2259%3A2517)

Screen 3 - Set Reminder drop-down
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=2259%3A2674)

Screen 4 - Set recurrence repeat every drop-down
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=2259%3A2826)

**Comment by altBeck** [comment]
I worked on custom recurrence, I styled and positioned the elements within it's container

**Comment by altBeck** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/60580719/132125458-7911b9f8-db7e-4275-b422-3a5d3169708f.png)

**Comment by altBeck** [comment]
I worked on custom recurrence, I styled and positioned the elements within its container. Below is a screenshot of my completed task.
![Screenshot (37)](https://user-images.githubusercontent.com/60580719/132125530-81da2d0a-341c-4200-b5fe-99f263f227db.png)

**Comment by altBeck** [comment]
I worked on the custom recurrence popup, I styled the elements in its containers. Below is a screenshot of my completed task.
![Screenshot (39)](https://user-images.githubusercontent.com/60580719/132125643-3918c6fa-fdff-439f-bda2-b034ace4eee2.png)
