### ISSUE TITLE
Design system(buttons and components)

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#212]

**Comment by simileoluwa** [comment]
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=1319%3A1506)

**Comment by simileoluwa** [comment]
(https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=10%3A673)
