### ISSUE TITLE
Create an endpoint  that displays information about the plugin in Json format.

### ISSUE THREAD

**Issue by Richardjackson-web** [zurichat/zc_plugin_company_holiday_calendar#215]

**Comment by Duvie728** [comment]
@Duvie728

**Comment by Duvie728** [comment]
Description
This change adds relevant fields to the JSON data returned by '/info' route. It also adds the '/ping' route.

Fixes #215 (issue)

How Has This Been Tested?
Visiting http://127.0.0.1:5500/info when the server is running in development mode & visiting  http://calendar.zuri.chat/info when the change goes live.

Visiting http://127.0.0.1:5500/ping when the server is running in development mode & visiting http://calendar.zuri.chat/ping when the change goes live.

Checklist:
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas (N/A)
 I have made corresponding changes to the documentation (N/A)
 My changes generate no lint warnings
