### ISSUE TITLE
Button to open the event form sidebar

### ISSUE THREAD

**Issue by Richardjackson-web** [zurichat/zc_plugin_company_holiday_calendar#222]
As a user I need a button that opens the event form when clicked.

**Comment by adeoyevictor** [comment]
I've added the button that opens the event form sidebar when clicked. See screenshot below


![ss8](https://user-images.githubusercontent.com/79271707/132084604-22f50dc1-b162-4ab3-802b-b8ec3f828ed4.JPG)
