### ISSUE TITLE
Add event and reminder tab buttons on the event form sidebar.

### ISSUE THREAD

**Issue by Richardjackson-web** [zurichat/zc_plugin_company_holiday_calendar#229]

**Comment by Godswilldev** [comment]
I've Created event and reminder tab buttons and added functionality for toggling between the event and reminder pages.
![Screenshot_20210904-074811](https://user-images.githubusercontent.com/71720298/132085610-7bb430d5-7b21-462a-a44c-81676f9de2de.png)
![Screenshot_20210904-074815](https://user-images.githubusercontent.com/71720298/132085613-01cb8a4f-3d8a-4a42-8ddf-8ae25f47d406.png)
