### ISSUE TITLE
Create utility that reads and write from go API db

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#240]

**Comment by itszona** [comment]
I'll  handle this

**Comment by itszona** [comment]
Created API Endpoint that creates an event, serializes it and saves it to the Zuri Core DB.

**Comment by itszona** [comment]
![Screenshot (208)](https://user-images.githubusercontent.com/89066735/132106854-c6328106-da77-4b22-8946-b543b59cde16.png)
![Screenshot (209)](https://user-images.githubusercontent.com/89066735/132106862-1921505c-f874-49eb-ab3e-84df0a3a2b17.png)

**Comment by itszona** [comment]
Live link : https://calendar.zuri.chat/zuricalendar/create_event_db/
**Slack Name: Zona**
