### ISSUE TITLE
Custom Recurrence for Company Holiday.

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#294]
As a User, I want to be able to custom recurrent reminders so that I am up to date with holidays

**Comment by ChukkyWang** [comment]
Custom Recurrence #286

Live Link: https://calendar.zuri.chat/

### How to view contribution.

- Go to the Live Link: [https://calendar.zuri.chat/](https://calendar.zuri.chat/)
- Click on the **Add Event** button on the **Navigation Bar**
- Click on the **Reminder** button on the pop-up.
- Click on the **Create** button which reveals a dropdown with options to choose from. Select **Custom...**
- The Custom Recurrence component as shown in the image below is revealed.

![Custom Recurrence Implementation](https://user-images.githubusercontent.com/63220512/132106060-8fdbab88-2571-4e64-918a-684384bbb03f.jpeg)
