### ISSUE TITLE
Create a start and end time input dropdown

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#301]

**Comment by Nifemiii** [comment]
I created a user input dropdown for entering the start and end time for an event the user wants to create
![Screenshot (3)_LI](https://user-images.githubusercontent.com/66307468/132120100-715ddd55-3e9e-4921-8b2a-e732185409ba.jpg)

**Comment by Nifemiii** [comment]
PR link: https://github.com/zurichat/zc_plugin_company_holiday_calendar/pull/300
