### ISSUE TITLE
Add description input to event form

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#315]
As a user, I want the add event form to contain an input form so that I can add more details about the event.

**Comment by evidencebeke** [comment]
I added an some icons and an input for the user to describe the event in the Add event pop-up

**Comment by evidencebeke** [comment]
PR Link: https://github.com/zurichat/zc_plugin_company_holiday_calendar/pull/308

**Comment by evidencebeke** [comment]
![IMG-20210905-WA0001](https://user-images.githubusercontent.com/67022912/132119779-62c63eb6-f0c0-4bc8-8d69-6ab43115fe88.jpg)
