### ISSUE TITLE
Add a date input component on the event page

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#316]

**Comment by SeunPaul** [comment]
**How to view contribution**.

- Go to the Live Link: https://calendar.zuri.chat/
- Click on the Add Event button on the Navigation Bar
- The Date inputs - start date and end date will be seen as shown in the image below
- Click on it to pick a date

![image](https://user-images.githubusercontent.com/51615334/132123451-fe8c17e2-1c7b-4944-a4af-aba9a1cab5cf.png)
