### ISSUE TITLE
customRecurre

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#338]
For users to customize their remainder

**Comment by Purple19-dev** [comment]
custom Recurrene #337

Live link  https://calendar.zuri.chat/

### **How to  view contribution**

1.  Visit the link https://calendar.zuri.chat/
2.  Click on add event button on the nav bar
3.  Click on the reminder button below the navbar
4.  Click on create drop-down button to set a reminder
5. On the drop-down button select custom...
6. On the custom Recurrence page click on the dates input form and select a dates on the pop calendar as shown below to set your reminder date


![iMarkup_20210906_154834](https://user-images.githubusercontent.com/76389313/132234754-f58cc55e-437c-45f3-89b3-be0d75c8e7fd.jpg)
