### ISSUE TITLE
Rewrite serializer class for event and remove the default django model

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#340]
in serializers.py remove the current event model and initialize serializers fields for events which will be used to develop the CREATE api view and endpoints which will write into zuri core database.

**Comment by Duvie728** [comment]
Accepted. Thank you

**Comment by aayobam** [comment]
in serializers.py remove the current event model and initialize serializers fields for events which will be used to develop the CREATE api view and endpoints which will write into zuri core database.
