### ISSUE TITLE
Develop CREATE api view endpoint for event 

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#341]
Rewrite a create view that consumes zuri core's api and save data to zuri core database.do not use django model and do not commit the db.sqlite3.

**Comment by Duvie728** [comment]
Thank you

**Comment by aayobam** [comment]
Develop a create view that consumes zuri core's api and save data to zuri core database.do not use django model and do not commit the db.sqlite3.
