### ISSUE TITLE
Create DETAIL view api endpoint for event

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#350]
Rewrite a Detail view and endpoint that consumes zuri core's api and fetch data from zuri core database. Do not use django model and do not commit the db.sqlite3.

**Comment by MickeyLannister17** [comment]
Lanister

**Comment by MickeyLannister17** [comment]
Lannister

**Comment by aayobam** [comment]
closing the issue as its a replica of another issue.
