### ISSUE TITLE
create a FILTER/SEARCH api view and endpoint for event

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#353]
Create a Filter/Search api view and endpoint that filters event details from zuri core database.

**Comment by Ifeadewumi** [comment]
If nobody has picked this before, I'll work on it.

**Comment by aayobam** [comment]
Alright, you have been assigned.

**Comment by 50-Course** [comment]
Would love to work on this feature.

**Comment by Ifeadewumi** [comment]
Kindly reassign task to me (@Ifeadewumi), @aayobam. 

Thank you.
