### ISSUE TITLE
Add event views,

### ISSUE THREAD

**Issue by aayobam** [zurichat/zc_plugin_company_holiday_calendar#70]
As an employee I want to view a single event  so I can see that event's information

**Comment by kanikamital0606** [comment]
I've styled the event page month-wise so you can view all events same time

**Comment by kanikamital0606** [comment]
![Screenshot (106)](https://user-images.githubusercontent.com/62260571/132065388-325f39e4-b92c-4d4b-bb4f-56829144353c.png)

Here is the final output

**Comment by kanikamital0606** [comment]
https://github.com/kanikamital0606/zc_plugin_company_holiday_calendar 
Link to updated code

**Comment by kanikamital0606** [comment]
The changes you can see here 
https://github.com/zurichat/zc_plugin_company_holiday_calendar/commit/75e8ccfceea4082c5a0e5f54da7a2f6c1e8a3759#diff-7bc5151e2b5ff04ab42da1676358e8531c088ac02703f5695869eccff4f9fede
